# Generated by Django 2.2.10 on 2020-07-21 10:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=12)),
                ('contact_person', models.CharField(max_length=1500)),
                ('number', models.CharField(max_length=12)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('category', models.CharField(choices=[('General', 'General'), ('Marketing', 'Marketing'), ('Energy', 'Energy'), ('Iot', 'Iot'), ('Automation', 'Automation')], max_length=500)),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('file1', models.ImageField(blank=True, null=True, upload_to='')),
                ('file2', models.ImageField(blank=True, null=True, upload_to='')),
                ('file3', models.ImageField(blank=True, null=True, upload_to='')),
                ('file4', models.FileField(blank=True, null=True, upload_to='')),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('tags', models.CharField(default='', max_length=2500)),
                ('deadline', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='OPEN', max_length=100)),
                ('slug', models.SlugField()),
            ],
            options={
                'unique_together': {('title', 'date_posted')},
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('sfile', models.FileField(blank=True, null=True, upload_to='')),
                ('submitted_on', models.DateField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostChallenge.Challenges')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4000)),
                ('content', models.TextField()),
                ('video', models.FileField(upload_to='')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField()),
                ('datePosted', models.DateField(auto_now_add=True)),
                ('tags', models.CharField(max_length=1000)),
                ('approved', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=500, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
            options={
                'unique_together': {('title', 'datePosted')},
            },
        ),
    ]
