# Generated by Django 2.2.10 on 2020-04-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostChallenge', '0004_auto_20200429_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='datePosted',
            field=models.DateField(auto_now_add=True, default='2020-05-06'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.CharField(choices=[('Machine', 'Machine'), ('Machine', 'Machine'), ('Machine', 'Machine'), ('Machine', 'Machine'), ('Machine', 'Machine')], default='Machine', max_length=100),
            preserve_default=False,
        ),
    ]
