# Generated by Django 2.2.10 on 2020-04-30 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_gstin'),
        ('hostChallenge', '0005_auto_20200430_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.CharField(choices=[('Machine', 'Machine'), ('Materials', 'Materials'), ('Machine', 'Machine'), ('Machine', 'Machine'), ('Machine', 'Machine')], max_length=100),
        ),
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('challenge_file', models.FileField(upload_to='')),
                ('date_posted', models.DateField()),
                ('slug', models.SlugField()),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
            options={
                'unique_together': {('title', 'date_posted')},
            },
        ),
    ]
