# Generated by Django 2.2.10 on 2020-04-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostChallenge', '0006_auto_20200430_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='category',
            field=models.CharField(default='Csd', max_length=500),
            preserve_default=False,
        ),
    ]
