# Generated by Django 2.2.10 on 2020-04-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostChallenge', '0007_challenges_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='challenge_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
