# Generated by Django 2.2.10 on 2020-04-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostChallenge', '0008_auto_20200430_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
