# Generated by Django 2.2.10 on 2020-04-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostChallenge', '0009_auto_20200430_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
