# Generated by Django 2.2.10 on 2020-05-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostChallenge', '0010_challenges_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='challenges',
            name='tags',
            field=models.CharField(default='', max_length=2500),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='category',
            field=models.CharField(choices=[('Marketing', 'Marketing'), ('Energy', 'Energy'), ('Iot', 'Iot'), ('Automation', 'Automation')], max_length=500),
        ),
    ]
