# Generated by Django 2.2.10 on 2020-05-10 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hostChallenge', '0011_auto_20200510_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
