# Generated by Django 2.2.10 on 2020-05-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostChallenge', '0012_challenges_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='status',
            field=models.CharField(default='OPEN', max_length=100),
        ),
    ]
