# Generated by Django 2.2.10 on 2020-05-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostChallenge', '0013_challenges_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
