# Generated by Django 2.2.10 on 2020-05-10 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostChallenge', '0014_challenges_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenges',
            name='video',
        ),
    ]
