# Generated by Django 2.2.10 on 2020-05-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostChallenge', '0015_remove_challenges_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenges',
            old_name='challenge_file',
            new_name='file1',
        ),
        migrations.AddField(
            model_name='challenges',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='challenges',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='challenges',
            name='file4',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
