# Generated by Django 2.2.10 on 2020-05-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostChallenge', '0016_auto_20200510_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='file1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='file2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='file3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
