# Generated by Django 2.2.10 on 2020-05-10 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostChallenge', '0017_auto_20200510_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenges',
            name='posted_by',
        ),
    ]
