# Generated by Django 2.2.10 on 2020-05-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostChallenge', '0018_remove_challenges_posted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=12)),
                ('contact_person', models.CharField(max_length=1500)),
                ('number', models.CharField(max_length=12)),
            ],
        ),
    ]
