# Generated by Django 2.2.10 on 2020-05-10 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hostChallenge', '0019_challengecontacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengecontacts',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
