# Generated by Django 2.2.10 on 2020-05-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostChallenge', '0021_submissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='sfile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
