# Generated by Django 2.2.10 on 2020-05-13 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hostChallenge', '0023_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='submitted_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
