# Generated by Django 2.2.10 on 2020-07-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostChallenge', '0027_auto_20200524_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Marketing', 'Marketing'), ('Energy', 'Energy'), ('Iot', 'Iot'), ('Automation', 'Automation')], max_length=500),
        ),
    ]
