# Generated by Django 2.2.10 on 2020-07-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostChallenge', '0028_auto_20200717_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
