# Generated by Django 2.2.10 on 2020-07-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostChallenge', '0029_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='sub_category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
